#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'cd e2e-openshift && git checkout func-test && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-functional/4ZWU-STS-Volume-Distribution/volume-distribution node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)
echo "*********Applying e2e-crd***********"
kubectl apply -f Openshift-EE/utils/e2e-crd.yml
echo "*****Deploying openebs*******"
bash Openshift-EE/utils/e2e-cr jobname:volume-replica-distribution jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:volume-replica-distribution jobphase:Running init_time:"$current_time"

# Removing test_id from e2e-result.yml spec for simple mode
sed -i "s/-<job_id>/ /g" Openshift-EE/utils/e2e-result.yml

echo "****Creating e2e-crd********"
cat Openshift-EE/utils/e2e-result.yml > volume-distribution-$job_id.yml
sed -i -e "s/<test-phase>/Running/g" -e "s/<test-name>/sts-volume-distribution/g" -e"s/<job_id>/$job_id/g" volume-distribution-$job_id.yml

time="date"
current_time=$(eval $time)
sed -i -e "s/<test-init>/$current_time/g" -e "s/<openebs-id>/0.8.1/g" volume-distribution-$job_id.yml
kubectl apply -f volume-distribution-$job_id.yml
cat volume-distribution-$job_id.yml

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=replica-distribution metadata="")
echo $test_name

echo "*******Deploying Application and Check the statefulset storage volume distributed************"
cd litmus
echo "Running the litmus test.."
run_test=apps/busybox/functional/volume-distribution/run_litmus_test.yml
cat $run_test
sleep 15

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-statefulset-litmus' job=$run_test

echo "Dumping state of cluster post job run"; echo ""
bash ../Openshift-EE/utils/dump_cluster_state;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource

cd .. && bash Openshift-EE/utils/get_litmus_result ${test_name} volume-replica-distribution
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
